image: docker:latest

variables:
  APP: passport-service # ECR container
  LABEL: passport # LABEL=subdomain, example - https://$LABEL.yellowimages.com/
  ARGOCD_PATH_SERVICE: services/passport # git - yellowimages/infrastructure/yi-kube-cd/-/tree/stage/getyellow

services:
  - docker:dind

stages:
  - security
  - build
  - deploy-tag

before_script:
  - docker info
  - which aws || apk add --no-cache curl jq python3 py-pip
  - which aws || pip install awscli

security_checker:
  tags:
    - docker
  stage: security
  script:
    - apk add bash
    - ./security_checker.sh

include:
- project: yellowimages/infrastructure/gitlab-cicd
  file: ci-Build.gitlab-ci.yml
  ref: master
- project: yellowimages/infrastructure/gitlab-cicd
  file: cd-Deploy-Tag.gitlab-ci.yml
  ref: master
