GET https://yellowimages.com/sso/register.php?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpZCI6NCwiZmlyc3RfbmFtZSI6InNkYXNhZG0iLCJsYXN0X25hbWUiOiJkZnNwanNkaXBqIiwiZW1haWwiOiJhc2Rqc2ZkQHlhLnJ1IiwiZXhwaXJlZF9hdCI6MTY2OTMzOTEyNSwiY2FsbGJhY2siOiJodHRwczovL2dldHllbGxvdy54eXovcmVnaXN0YXRpb24vY29uZmlybSJ9.bIf-m6-pWL5tBUv7o9p8ipXsNGLfbVNq25qfjVwv4kYnGMXg4EwVAeRSc9OAeq-VdH6QvbjFhCOaI2Foyz54e6fRtu-sw2tSlrmQRLScA2GN-moIVk8xjMBUTfD5NlxxDEUqUpT8rvlDVN76FqXtORlgsnwTJfB8YY8oLuJg09dXzrgu2iJeIpWz4NC2PBDf4PSK08JFF0oja7bG2mcPCMwgj9nMt9H2hMjQ2KWidel0w2aKLJitNMXasd7Dj37jkRn5Lf7L9Phf3wqV3dx5UWM3w0Q2MobDCy31wlGaoDbjgF1GUxykjkaFf-Jbh6WXPCYr0xeg9yP7qwljem9BWg
